name: gradle-build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkstyle:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle', '**/settings.gradle.kts') }}
          restore-keys: |
            gradle-
      - run: ./gradlew build